### ISSUE TITLE
Bug Report: Incorrect Task Count Update in "Important" Menu

### ISSUE THREAD

**Issue by Naandalist** [Naandalist/luminariest#2]
### Reproduce Bug:

1. **Navigate to:** Click on the "Important" menu. You should see a list of 4 tasks.
2. **Delete First Task:** Delete the first task, which is "menelpon Ibu."
3. **Unexpected Behavior:** After clicking the delete button, the app redirects to the "All Tasks" view. However, the total number of tasks displayed under the "Important" menu does not update immediately. It should show 3 remaining tasks, but instead, the count only updates correctly after clicking back the "Important" menu again.

### Expected Behavior:
Total number of tasks under the "Important" menu should update in real-time whenever a task is deleted. This would ensure that the displayed count always reflects the accurate number of tasks in that category.

https://github.com/user-attachments/assets/c6def65c-7757-4cdf-b468-0841fc2ec20e

**Comment by mhaidarhanif** [comment]
@Naandalist Probably because after clicking/submitting the "Delete" action, the global/root loader didn't refetch/revalidate the new data condition yet.

- Either properly check the global/root loader to trigger after the action
- Or check the behavior by following https://reactrouter.com/en/main/route/should-revalidate and https://reactrouter.com/en/main/hooks/use-revalidator

**Comment by mhaidarhanif** [comment]
@Naandalist I've tried to reproduce the issue multiple times, but it seems to work just fine, no bug found.
